using BlazorConference.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlazorConference.Services
{
    public class CountryService
    {
        public static List<Country> GetCountries()
        {
            return new List<Country>() {
                                    new Country { CountryAbbr="AF", CountryName="Afghanistan" },
                                    new Country { CountryAbbr="AX", CountryName="Aland Islands" },
                                    new Country { CountryAbbr="AL", CountryName="Albania" },
                                    new Country { CountryAbbr="DZ", CountryName="Algeria" },
                                    new Country { CountryAbbr="AS", CountryName="American Samoa" },
                                    new Country { CountryAbbr="AD", CountryName="Andorra" },
                                    new Country { CountryAbbr="AO", CountryName="Angola" },
                                    new Country { CountryAbbr="AI", CountryName="Anguilla" },
                                    new Country { CountryAbbr="AQ", CountryName="Antarctica" },
                                    new Country { CountryAbbr="AG", CountryName="Antigua and Barbuda" },
                                    new Country { CountryAbbr="AR", CountryName="Argentina" },
                                    new Country { CountryAbbr="AM", CountryName="Armenia" },
                                    new Country { CountryAbbr="AW", CountryName="Aruba" },
                                    new Country { CountryAbbr="AU", CountryName="Australia" },
                                    new Country { CountryAbbr="AT", CountryName="Austria" },
                                    new Country { CountryAbbr="AZ", CountryName="Azerbaijan" },
                                    new Country { CountryAbbr="BS", CountryName="Bahamas" },
                                    new Country { CountryAbbr="BH", CountryName="Bahrain" },
                                    new Country { CountryAbbr="BD", CountryName="Bangladesh" },
                                    new Country { CountryAbbr="BB", CountryName="Barbados" },
                                    new Country { CountryAbbr="BE", CountryName="Belgium" },
                                    new Country { CountryAbbr="BZ", CountryName="Belize" },
                                    new Country { CountryAbbr="BJ", CountryName="Benin" },
                                    new Country { CountryAbbr="BM", CountryName="Bermuda" },
                                    new Country { CountryAbbr="BT", CountryName="Bhutan" },
                                    new Country { CountryAbbr="BO", CountryName="Bolivia" },
                                    new Country { CountryAbbr="BA", CountryName="Bosnia and Herzegovina" },
                                    new Country { CountryAbbr="BW", CountryName="Botswana" },
                                    new Country { CountryAbbr="BV", CountryName="Bouvet Island" },
                                    new Country { CountryAbbr="BR", CountryName="Brazil" },
                                    new Country { CountryAbbr="IO", CountryName="British Indian Ocean Territory" },
                                    new Country { CountryAbbr="BN", CountryName="Brunei Darussalam" },
                                    new Country { CountryAbbr="BG", CountryName="Bulgaria" },
                                    new Country { CountryAbbr="BF", CountryName="Burkina Faso" },
                                    new Country { CountryAbbr="BI", CountryName="Burundi" },
                                    new Country { CountryAbbr="KH", CountryName="Cambodia" },
                                    new Country { CountryAbbr="CM", CountryName="Cameroon" },
                                    new Country { CountryAbbr="CA", CountryName="Canada" },
                                    new Country { CountryAbbr="CV", CountryName="Cape Verde" },
                                    new Country { CountryAbbr="KY", CountryName="Cayman Islands" },
                                    new Country { CountryAbbr="CF", CountryName="Central African Republic" },
                                    new Country { CountryAbbr="TD", CountryName="Chad" },
                                    new Country { CountryAbbr="CL", CountryName="Chile" },
                                    new Country { CountryAbbr="CN", CountryName="China" },
                                    new Country { CountryAbbr="CX", CountryName="Christmas Island" },
                                    new Country { CountryAbbr="CC", CountryName="Cocos (Keeling) Islands" },
                                    new Country { CountryAbbr="CO", CountryName="Colombia" },
                                    new Country { CountryAbbr="KM", CountryName="Comoros" },
                                    new Country { CountryAbbr="CK", CountryName="Cook Islands" },
                                    new Country { CountryAbbr="CR", CountryName="Costa Rica" },
                                    new Country { CountryAbbr="HR", CountryName="Croatia" },
                                    new Country { CountryAbbr="CY", CountryName="Cyprus" },
                                    new Country { CountryAbbr="CZ", CountryName="Czech Republic" },
                                    new Country { CountryAbbr="DK", CountryName="Denmark" },
                                    new Country { CountryAbbr="DJ", CountryName="Djibouti" },
                                    new Country { CountryAbbr="DM", CountryName="Dominica" },
                                    new Country { CountryAbbr="DO", CountryName="Dominican Republic" },
                                    new Country { CountryAbbr="EC", CountryName="Ecuador" },
                                    new Country { CountryAbbr="EG", CountryName="Egypt" },
                                    new Country { CountryAbbr="SV", CountryName="El Salvador" },
                                    new Country { CountryAbbr="GQ", CountryName="Equatorial Guinea" },
                                    new Country { CountryAbbr="ER", CountryName="Eritrea" },
                                    new Country { CountryAbbr="EE", CountryName="Estonia" },
                                    new Country { CountryAbbr="ET", CountryName="Ethiopia" },
                                    new Country { CountryAbbr="FK", CountryName="Falkland Islands" },
                                    new Country { CountryAbbr="FO", CountryName="Faroe Islands" },
                                    new Country { CountryAbbr="FJ", CountryName="Fiji" },
                                    new Country { CountryAbbr="FI", CountryName="Finland" },
                                    new Country { CountryAbbr="FR", CountryName="France" },
                                    new Country { CountryAbbr="GF", CountryName="French Guiana" },
                                    new Country { CountryAbbr="PF", CountryName="French Polynesia" },
                                    new Country { CountryAbbr="TF", CountryName="French Southern Territories" },
                                    new Country { CountryAbbr="GA", CountryName="Gabon" },
                                    new Country { CountryAbbr="GM", CountryName="Gambia" },
                                    new Country { CountryAbbr="GE", CountryName="Georgia" },
                                    new Country { CountryAbbr="DE", CountryName="Germany" },
                                    new Country { CountryAbbr="GH", CountryName="Ghana" },
                                    new Country { CountryAbbr="GI", CountryName="Gibraltar" },
                                    new Country { CountryAbbr="GR", CountryName="Greece" },
                                    new Country { CountryAbbr="GL", CountryName="Greenland" },
                                    new Country { CountryAbbr="GD", CountryName="Grenada" },
                                    new Country { CountryAbbr="GP", CountryName="Guadeloupe" },
                                    new Country { CountryAbbr="GU", CountryName="Guam" },
                                    new Country { CountryAbbr="GT", CountryName="Guatemala" },
                                    new Country { CountryAbbr="GG", CountryName="Guernsey" },
                                    new Country { CountryAbbr="GN", CountryName="Guinea" },
                                    new Country { CountryAbbr="GW", CountryName="Guinea-Bissau" },
                                    new Country { CountryAbbr="GY", CountryName="Guyana" },
                                    new Country { CountryAbbr="HT", CountryName="Haiti" },
                                    new Country { CountryAbbr="HM", CountryName="Heard Island and Mcdonald Islands" },
                                    new Country { CountryAbbr="HN", CountryName="Honduras" },
                                    new Country { CountryAbbr="HK", CountryName="Hong Kong" },
                                    new Country { CountryAbbr="HU", CountryName="Hungary" },
                                    new Country { CountryAbbr="IS", CountryName="Iceland" },
                                    new Country { CountryAbbr="IN", CountryName="India" },
                                    new Country { CountryAbbr="ID", CountryName="Indonesia" },
                                    new Country { CountryAbbr="IE", CountryName="Ireland" },
                                    new Country { CountryAbbr="IM", CountryName="Isle of Man" },
                                    new Country { CountryAbbr="IL", CountryName="Israel" },
                                    new Country { CountryAbbr="IT", CountryName="Italy" },
                                    new Country { CountryAbbr="JM", CountryName="Jamaica" },
                                    new Country { CountryAbbr="JP", CountryName="Japan" },
                                    new Country { CountryAbbr="JE", CountryName="Jersey" },
                                    new Country { CountryAbbr="JO", CountryName="Jordan" },
                                    new Country { CountryAbbr="KZ", CountryName="Kazakhstan" },
                                    new Country { CountryAbbr="KE", CountryName="Kenya" },
                                    new Country { CountryAbbr="KI", CountryName="Kiribati" },
                                    new Country { CountryAbbr="KW", CountryName="Kuwait" },
                                    new Country { CountryAbbr="KG", CountryName="Kyrgyzstan" },
                                    new Country { CountryAbbr="LA", CountryName="Laos" },
                                    new Country { CountryAbbr="LV", CountryName="Latvia" },
                                    new Country { CountryAbbr="LS", CountryName="Lesotho" },
                                    new Country { CountryAbbr="LR", CountryName="Liberia" },
                                    new Country { CountryAbbr="LY", CountryName="Libya" },
                                    new Country { CountryAbbr="LI", CountryName="Liechtenstein" },
                                    new Country { CountryAbbr="LT", CountryName="Lithuania" },
                                    new Country { CountryAbbr="LU", CountryName="Luxembourg" },
                                    new Country { CountryAbbr="MO", CountryName="Macao" },
                                    new Country { CountryAbbr="MK", CountryName="Macedonia, Republic of" },
                                    new Country { CountryAbbr="MG", CountryName="Madagascar" },
                                    new Country { CountryAbbr="MW", CountryName="Malawi" },
                                    new Country { CountryAbbr="MY", CountryName="Malaysia" },
                                    new Country { CountryAbbr="MV", CountryName="Maldives" },
                                    new Country { CountryAbbr="ML", CountryName="Mali" },
                                    new Country { CountryAbbr="MT", CountryName="Malta" },
                                    new Country { CountryAbbr="MH", CountryName="Marshall Islands" },
                                    new Country { CountryAbbr="MQ", CountryName="Martinique" },
                                    new Country { CountryAbbr="MR", CountryName="Mauritania" },
                                    new Country { CountryAbbr="MU", CountryName="Mauritius" },
                                    new Country { CountryAbbr="YT", CountryName="Mayotte" },
                                    new Country { CountryAbbr="MX", CountryName="Mexico" },
                                    new Country { CountryAbbr="FM", CountryName="Micronesia" },
                                    new Country { CountryAbbr="MD", CountryName="Moldova" },
                                    new Country { CountryAbbr="MC", CountryName="Monaco" },
                                    new Country { CountryAbbr="MN", CountryName="Mongolia" },
                                    new Country { CountryAbbr="ME", CountryName="Montenegro" },
                                    new Country { CountryAbbr="MS", CountryName="Montserrat" },
                                    new Country { CountryAbbr="MA", CountryName="Morocco" },
                                    new Country { CountryAbbr="MZ", CountryName="Mozambique" },
                                    new Country { CountryAbbr="MM", CountryName="Myanmar" },
                                    new Country { CountryAbbr="NA", CountryName="Namibia" },
                                    new Country { CountryAbbr="NR", CountryName="Nauru" },
                                    new Country { CountryAbbr="NP", CountryName="Nepal" },
                                    new Country { CountryAbbr="NL", CountryName="Netherlands" },
                                    new Country { CountryAbbr="AN", CountryName="Netherlands Antilles" },
                                    new Country { CountryAbbr="NC", CountryName="New Caledonia" },
                                    new Country { CountryAbbr="NZ", CountryName="New Zealand" },
                                    new Country { CountryAbbr="NI", CountryName="Nicaragua" },
                                    new Country { CountryAbbr="NE", CountryName="Niger" },
                                    new Country { CountryAbbr="NG", CountryName="Nigeria" },
                                    new Country { CountryAbbr="NU", CountryName="Niue" },
                                    new Country { CountryAbbr="NF", CountryName="Norfolk Island" },
                                    new Country { CountryAbbr="MP", CountryName="Northern Mariana Islands" },
                                    new Country { CountryAbbr="NO", CountryName="Norway" },
                                    new Country { CountryAbbr="OM", CountryName="Oman" },
                                    new Country { CountryAbbr="PK", CountryName="Pakistan" },
                                    new Country { CountryAbbr="PW", CountryName="Palau" },
                                    new Country { CountryAbbr="PS", CountryName="Palestinian Territories" },
                                    new Country { CountryAbbr="PA", CountryName="Panama" },
                                    new Country { CountryAbbr="PG", CountryName="Papua New Guinea" },
                                    new Country { CountryAbbr="PY", CountryName="Paraguay" },
                                    new Country { CountryAbbr="PE", CountryName="Peru" },
                                    new Country { CountryAbbr="PH", CountryName="Philippines" },
                                    new Country { CountryAbbr="PN", CountryName="Pitcairn" },
                                    new Country { CountryAbbr="PL", CountryName="Poland" },
                                    new Country { CountryAbbr="PT", CountryName="Portugal" },
                                    new Country { CountryAbbr="PR", CountryName="Puerto Rico" },
                                    new Country { CountryAbbr="QA", CountryName="Qatar" },
                                    new Country { CountryAbbr="RE", CountryName="Reunion" },
                                    new Country { CountryAbbr="RO", CountryName="Romania" },
                                    new Country { CountryAbbr="RU", CountryName="Russian Federation" },
                                    new Country { CountryAbbr="RW", CountryName="Rwanda" },
                                    new Country { CountryAbbr="BL", CountryName="Saint Barthelemy" },
                                    new Country { CountryAbbr="SH", CountryName="Saint Helena" },
                                    new Country { CountryAbbr="KN", CountryName="Saint Kitts and Nevis" },
                                    new Country { CountryAbbr="LC", CountryName="Saint Lucia" },
                                    new Country { CountryAbbr="MF", CountryName="Saint Martin" },
                                    new Country { CountryAbbr="PM", CountryName="Saint Pierre and Miquelon" },
                                    new Country { CountryAbbr="VC", CountryName="Saint Vincent and the Grenadines" },
                                    new Country { CountryAbbr="WS", CountryName="Samoa" },
                                    new Country { CountryAbbr="SM", CountryName="San Marino" },
                                    new Country { CountryAbbr="ST", CountryName="Sao Tome and Principe" },
                                    new Country { CountryAbbr="SA", CountryName="Saudi Arabia" },
                                    new Country { CountryAbbr="SN", CountryName="Senegal" },
                                    new Country { CountryAbbr="RS", CountryName="Serbia" },
                                    new Country { CountryAbbr="SC", CountryName="Seychelles" },
                                    new Country { CountryAbbr="SL", CountryName="Sierra Leone" },
                                    new Country { CountryAbbr="SG", CountryName="Singapore" },
                                    new Country { CountryAbbr="SK", CountryName="Slovakia" },
                                    new Country { CountryAbbr="SI", CountryName="Slovenia" },
                                    new Country { CountryAbbr="SB", CountryName="Solomon Islands" },
                                    new Country { CountryAbbr="ZA", CountryName="South Africa" },
                                    new Country { CountryAbbr="GS", CountryName="South Georgia" },
                                    new Country { CountryAbbr="KR", CountryName="South Korea" },
                                    new Country { CountryAbbr="ES", CountryName="Spain" },
                                    new Country { CountryAbbr="LK", CountryName="Sri Lanka" },
                                    new Country { CountryAbbr="SR", CountryName="Suriname" },
                                    new Country { CountryAbbr="SJ", CountryName="Svalbard and Jan Mayen" },
                                    new Country { CountryAbbr="SZ", CountryName="Swaziland" },
                                    new Country { CountryAbbr="SE", CountryName="Sweden" },
                                    new Country { CountryAbbr="CH", CountryName="Switzerland" },
                                    new Country { CountryAbbr="TW", CountryName="Taiwan" },
                                    new Country { CountryAbbr="TJ", CountryName="Tajikistan" },
                                    new Country { CountryAbbr="TZ", CountryName="Tanzania, United Republic of" },
                                    new Country { CountryAbbr="TH", CountryName="Thailand" },
                                    new Country { CountryAbbr="TL", CountryName="Timor-Leste" },
                                    new Country { CountryAbbr="TG", CountryName="Togo" },
                                    new Country { CountryAbbr="TK", CountryName="Tokelau" },
                                    new Country { CountryAbbr="TO", CountryName="Tonga" },
                                    new Country { CountryAbbr="TT", CountryName="Trinidad and Tobago" },
                                    new Country { CountryAbbr="TN", CountryName="Tunisia" },
                                    new Country { CountryAbbr="TR", CountryName="Turkey" },
                                    new Country { CountryAbbr="TM", CountryName="Turkmenistan" },
                                    new Country { CountryAbbr="TC", CountryName="Turks and Caicos Islands" },
                                    new Country { CountryAbbr="TV", CountryName="Tuvalu" },
                                    new Country { CountryAbbr="UG", CountryName="Uganda" },
                                    new Country { CountryAbbr="UA", CountryName="Ukraine" },
                                    new Country { CountryAbbr="AE", CountryName="United Arab Emirates" },
                                    new Country { CountryAbbr="GB", CountryName="United Kingdom" },
                                    new Country { CountryAbbr="US", CountryName="United States" },
                                    new Country { CountryAbbr="UM", CountryName="United States Minor Outlying Islands" },
                                    new Country { CountryAbbr="UY", CountryName="Uruguay" },
                                    new Country { CountryAbbr="UZ", CountryName="Uzbekistan" },
                                    new Country { CountryAbbr="VU", CountryName="Vanuatu" },
                                    new Country { CountryAbbr="VA", CountryName="Vatican City" },
                                    new Country { CountryAbbr="VE", CountryName="Venezuela" },
                                    new Country { CountryAbbr="VN", CountryName="Viet Nam" },
                                    new Country { CountryAbbr="VG", CountryName="Virgin Islands, British" },
                                    new Country { CountryAbbr="VI", CountryName="Virgin Islands, U.S." },
                                    new Country { CountryAbbr="WF", CountryName="Wallis and Futuna" },
                                    new Country { CountryAbbr="EH", CountryName="Western Sahara" },
                                    new Country { CountryAbbr="YE", CountryName="Yemen" },
                                    new Country { CountryAbbr="ZM", CountryName="Zambia" }
                                    };
        }
    }
}
